test_absolute (__main__.TestExercice) ... FAIL
test_factorial (__main__.TestExercice) ... FAIL
test_prefixes (__main__.TestExercice) ... ok
test_summation (__main__.TestExercice) ... ok
test_verify_ages (__main__.TestExercice) ... FAIL

======================================================================
FAIL: test_absolute (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 22, in test_absolute
    'Mauvaise réponse'
AssertionError: Lists differ: [None, 5] != [5, 5]

First differing element 0:
None
5

- [None, 5]
+ [5, 5] : Mauvaise réponse

======================================================================
FAIL: test_factorial (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 62, in test_factorial
    'Mauvaise réponse'
AssertionError: Lists differ: [2, 12, 80640, 7257600] != [1, 6, 40320, 3628800]

First differing element 0:
2
1

- [2, 12, 80640, 7257600]
+ [1, 6, 40320, 3628800] : Mauvaise réponse

======================================================================
FAIL: test_verify_ages (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 77, in test_verify_ages
    'Mauvaise réponse'
AssertionError: Lists differ: [False, False, False, True, True, False] != [False, True, False, False, True, True, True, True, False]

First differing element 1:
False
True

Second list contains 3 additional elements.
First extra element 6:
True

- [False, False, False, True, True, False]
+ [False, True, False, False, True, True, True, True, False]
?         ++++++                         ++++++++++++
 : Mauvaise réponse

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=3)
